
path: E:\MyProjects\DL Object Detection YOLO Series\YOLOV8 Object Tracking\download data\data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: alpaca
